# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Open Door Coworking
email: jd@opendoorcoworking.com
description: "Open Door Coworking is LaPorte, Indiana's first coworking space for freelancers, entrepreneurs, and telecommuters to call home. Work independently; not alone."
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://www.opendoorcoworking.com" # the base hostname & protocol for your site
twitter_username: jddoesdev
github_username:  jddoesdev
author: J.D. Flynn


# Build settings
markdown: kramdown
permalink: pretty
comments: true