<div class="">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2983.212838619102!2d-86.73299968416507!3d41.60790897924461!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8811126e3a8b8933%3A0xb288fc420895174!2sOpen+Door+Coworking!5e0!3m2!1sen!2sus!4v1447384166381" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div><!--///////////////////////////////////////////////////////

  // End Contact section

  //////////////////////////////////////////////////////////-->

  <!--///////////////////////////////////////////////////////

  // Footer section

  //////////////////////////////////////////////////////////-->

  <div class="footer row-back">
    <div class="w-container wrap-normal center">
      © <strong>Open Door Coworking</strong> 2015 <a href="privacy.php" target="_blank">Privacy Policy</a>
    </div>
  </div>
  <!--///////////////////////////////////////////////////////

  // End Footer section

  //////////////////////////////////////////////////////////-->

  <!-- START JQUERY PLUGINS LOAD -->
  <script src="js/jquery.js"></script>
  <script src="js/modernizr.js"></script>
  <script src="js/normal.js"></script>
  <script src="js/carousels.js"></script>
  <script src="js/jquery.stellar.js"></script>
  <script src="js/classie.js"></script>
  <script src="js/jquery.mixitup.js"></script>
  <script src="js/testimonials.js"></script>
  <!-- <script src="js/jquery.nicescroll.js"></script> -->
  <script src="js/rotating-text.js"></script>
  <script src="js/jquery.magnific-popup.js"></script>
  <script src="js/headhesive.min.js"></script>
  <script src="js/waypoints.min.js"></script>
  <script src="js/contact.js"></script>
  <script src="js/lightbox.min.js"></script>
  <script src="js/scripts.js"></script>

  <!-- END JQUERY PLUGINS LOAD -->

</body>
</html>
