<!DOCTYPE html>
<html>

<head>
  <!-- START HEAD -->
  <meta charset="utf-8">
  <!-- Facebook Conversion Code for Key Page Views - James Flynn 1 -->
  <script>
  (function() {
    var _fbq = window._fbq || (window._fbq = []);
    if (!_fbq.loaded) {
      var fbds = document.createElement('script');
      fbds.async = true;
      fbds.src = '//connect.facebook.net/en_US/fbds.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(fbds, s);
      _fbq.loaded = true;
    }
  })();
  window._fbq = window._fbq || [];
  window._fbq.push(['track', '6038992278492', {
    'value' : '0.00',
    'currency' : 'USD'
  }]);
  </script>
  <noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6038992278492&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" />
  </noscript>
  <!-- START TITLE -->
  <title>Open Door Coworking | La Porte and Michigan City's FIRST Coworking Space</title>
  <!-- END TITLE -->

  <!-- START META, DESCRIPTION, KEYWORDS, AUTHOR -->
  <meta name="description" content="Open Door Coworking is LaPorte, Indiana's first coworking space for freelancers, entrepreneurs, and telecommuters to call home. Work independently; not alone." />
  <meta name="keywords" content="coworking, laporte, indiana, freelancer, entrepreneurs, office space rental, office space for rent" />
  <!-- END META, DESCRIPTION, KEYWORDS, AUTHOR -->

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- START THEME STYLE -->
  <link rel="stylesheet" type="text/css" href="css/normal.css">
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/headhesive.css">
  <link rel="stylesheet" type="text/css" href="css/lightbox.css">
  <link href="css/animate.css" rel="stylesheet">

  <!-- END THEME STYLE -->

  <!-- START FONTELLO ICONS STYLESHEET -->
  <link rel="stylesheet" type="text/css" href="css/fontello.css">
  <link rel="stylesheet" type="text/css" href="css/fontello-ie7.css">
  <!-- END FONTELLO ICONS STYLESHEET -->

  <!-- START MAGNIFIC POPUP STYLESHEET -->
  <link rel="stylesheet" type="text/css" href="css/magnific-popup.css">
  <!-- END MAGNIFIC POPUP STYLESHEET -->

  <!-- LOAD GOOGLE FONT OPEN SANS -->
  <link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700" rel="stylesheet" type="text/css">
  <!-- END GOOGLE FONT OPEN SANS -->

  <!-- START AJAX WEBFONTS -->
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <!-- END AJAX WEBFONTS -->

  <!-- START MOBILE DETECT -->
  <script>
  if (/mobile/i.test(navigator.userAgent))
  document.documentElement.className += ' w-mobile';
  </script>
  <!-- END MOBILE DETECT -->

  <!-- START FAVICON -->
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
  <!-- EDN FAVICON -->

  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <script>
  (function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] ||
    function() {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date();
    a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-69195133-1', 'auto');
  ga('send', 'pageview');

  </script>
  <meta property="fb:admins" content="1821615255" />
  <meta property="fb:app_id" content="1033170423401446" />
  <meta content="Open Door Coworking" property="og:site_name">
  <meta content="Open Door Coworking is LaPorte, Indiana's first coworking space for freelancers, entrepreneurs, and telecommuters to call home. Work independently; not alone." property="og:description">
  <meta content="http://www.opendoorcoworking.com/" property="og:url">
  <meta content="http://www.opendoorcoworking.com/images/opendoor.png" property="og:image">

  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@opendoorcowork">
  <meta name="twitter:creator" content="@jddoesdev">
  <meta name="twitter:title" content="Open Door Coworking">
  <meta name="twitter:url" content="http://www.opendoorcoworking.com/">
  <meta name="twitter:description" content="Open Door Coworking is LaPorte, Indiana's first coworking space for freelancers, entrepreneurs, and telecommuters to call home. Work independently; not alone.">
  <meta name="twitter:image:src" content="http://www.opendoorcoworking.com/images/opendoor.png">
</head><!-- END HEAD -->
<body>
  <!-- START BODY TAG -->

  <!-- START HEADER -->
  <!-- SCROLL DIV #boxscroll by nicescroll -->

  <div tabindex="1000" style="overflow-y: auto;" id="boxscroll">

    <!-- CHANGEABLE UNIQUE SECTOIN ID -->
    <section id="home">

      <!-- START FIXED HEADER DIV -->
      <div class="banner">
        <!-- START CONTAINER -->
        <div class="w-container container">
          <div class="w-row">

            <!-- START COLUMN 3 -->
            <div class="w-col w-col-2 logo">
              <!-- START LOGO -->
              <a href="#"><img src="images/opendoorcowork.png" alt="Open Door Coworking" onload="ga('send', 'event', 'page', 'load', 'Version <?php print $version; ?>');"></a>
              <!-- END LOGO -->
            </div><!-- END COLUMN 3 -->

            <!-- START COLUMN 9 -->
            <div class="nav-col w-col w-col-10">

              <!-- START NAVIGATION -->
              <div class="w-nav navbar" data-collapse="medium" data-animation="default" data-duration="400" data-contain="1">
                <div class="w-container nav">
                  <!-- START CONTAINER -->

                  <!-- START NAVIGATION LINKS -->
                  <nav class="w-nav-menu nav-menu" role="navigation">

                    <a class="w-nav-link menu-li " href="/" onclick="ga('send', 'event', 'menu', 'Click', 'Home');">HOME</a>
                    <a class="w-nav-link menu-li" href="membership/" onclick="ga('send', 'event', 'menu', 'Click', 'Membership');">MEMBERSHIP</a>
                    <a class="w-nav-link menu-li" href="contact-form/" onclick="ga('send', 'event', 'menu', 'Click', 'Contact');"> CONTACT </a>
                    <a class="w-nav-link menu-li" href="/faqs/" target="_blank" onclick="ga('send', 'event', 'menu', 'Click', 'Faqs');"> FAQs </a>
                    <a class="w-nav-link menu-li" href="/posts" onclick="ga('send', 'event', 'menu', 'Click', 'Blog');"> BLOG </a>
                    <a class="w-nav-link menu-li" href="/posts/events" onclick="ga('send', 'event', 'menu', 'Click', 'Blog');"> EVENTS </a>
                    <a class="w-nav-link menu-li social-nav" href="http://www.facebook.com/opendoorcoworking" onclick="ga('send', 'event', 'menu', 'Click', 'Facebook');"> <i class="facebookelegance-icons-"></i> </a>
                    <a class="w-nav-link menu-li social-nav" href="http://www.twitter.com/opendoorcowork" onclick="ga('send', 'event', 'menu', 'Click', 'Twitter');"> <i class="twitter-birdelegance-icons-"></i> </a>
                    <a class="w-nav-link menu-li social-nav" href="https://www.linkedin.com/company/open-door-coworking" onclick="ga('send', 'event', 'menu', 'Click', 'Linkedin');"> <i class="linkedinelegance-icons-"></i> </a>

                  </nav>
                  <!-- END NAVIGATION LINKS -->

                  <!-- START MOBILE NAVIGATION BUTTON * DO NOT DELETE THIS DIV* -->
                  <div class="w-nav-button">
                    <div class="w-icon-nav-menu"></div>
                  </div><!-- END MOBILE NAVIGATION BUTTON -->

                </div>
                <!-- END CONTAINER -->
              </div>
              <!-- END NAVIGATION -->
            </div>
            <!-- END COLUMN 9 -->
          </div>
        </div>
        <!-- END CONTAINER -->
      </div>
      <!-- END FIXED HEADER DIV -->
    </section>
    <!-- END SECTION -->
    <!-- END HEADER -->
