<script type='application/ld+json'>
{
  "@context": "http://schema.org",
  "@type": "LocalBusiness",
  "@id": "https://www.opendoorcoworking.com",
  "name": "Open Door Coworking",
  "url": "https://www.opendoorcoworking.com",
  "sameAs" : [
    "http://www.facebook.com/opendoorcoworking",
    "http://www.twitter.com/opendoorcowork",
    "http://www.yelp.com/biz/open-door-coworking-la-porte"
  ],
  "logo": "http://www.opendoorcoworking.com/images/opendoorcowork.png",
  "description": "Open Door Coworking is La Porte, Indiana's first coworking space for freelancers, entrepreneurs, and telecommuters. A coworking space is an alternative to traditional office space with a focus on creating a collaborative work community. Work. Together.",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+12195610219",
    "contactType" : "customer service"
  },
  "address": {
    "@type": "PostalAddress",
    "streetAddress" : "1705 State St",
    "addressLocality": "LaPorte",
    "addressRegion": "Indiana",
    "postalCode": "46350"
  }
}
</script>
